### root
GET http://localhost:3000

### list events
GET http://localhost:3000/events

### find one event
GET http://localhost:3000/events/{{ eventId}}


### create event
# @name createEvent
POST http://localhost:3000/events/
Content-Type: application/json

{
    "name": "Nasc Karl",
    "description": "Nascimento do doutor Carlos Marques",
    "date": "2020-05-16T00:00:00",
    "price": 100
}


###
@eventId = {{ createEvent.response.body.id }}


### update event
PATCH http://localhost:3000/events/{{ eventId }}
Content-Type: application/json

{
    "name": "Nasc Pep",
    "description": "Nascimento do Camarada Pep Mujica",
    "date": "2020-09-21T00:00:00",
    "price": 100
}


### delete event
DELETE http://localhost:3000/events/{{ eventId }}
